### ISSUE TITLE
Yellow-paper

### ISSUE THREAD

**Issue by gernotpokorny** [ArcBlock/Whitepaper#2]
Many good projects which have a whitepaper that is not very detailed (like Arcblock) have a yellow-paper including Ethereum. Since the Whitepaper is very abstract and not very detailed I have to ask the question if there will be a yellow-paper?

**Comment by mave99a** [comment]
Thanks for asking.  We will publish a series of "Blueprint" papers, it will serve the community sort of like Etherum's yellow paper, please stay tuned.
